name: Build and Test (Java CI with Maven)

on:
  push:
    branches:
      - master # Run on pushes to the master branch.
  pull_request:
    branches:
      - master # Run on pull requests targeting the master branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code (fetches the needed files to compile, test, ...).
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 8.
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin' # Or 'zulu'/'adopt'.

      # Step 3: Cache Maven dependencies.
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build with Maven.
      - name: Build and test
        run: mvn clean install
